// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: SimpleComm.proto

package SimpleComm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SimpleComm_Talk_FullMethodName = "/SimpleComm/Talk"
)

// SimpleCommClient is the client API for SimpleComm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleCommClient interface {
	Talk(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type simpleCommClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleCommClient(cc grpc.ClientConnInterface) SimpleCommClient {
	return &simpleCommClient{cc}
}

func (c *simpleCommClient) Talk(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, SimpleComm_Talk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleCommServer is the server API for SimpleComm service.
// All implementations must embed UnimplementedSimpleCommServer
// for forward compatibility
type SimpleCommServer interface {
	Talk(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSimpleCommServer()
}

// UnimplementedSimpleCommServer must be embedded to have forward compatible implementations.
type UnimplementedSimpleCommServer struct {
}

func (UnimplementedSimpleCommServer) Talk(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Talk not implemented")
}
func (UnimplementedSimpleCommServer) mustEmbedUnimplementedSimpleCommServer() {}

// UnsafeSimpleCommServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleCommServer will
// result in compilation errors.
type UnsafeSimpleCommServer interface {
	mustEmbedUnimplementedSimpleCommServer()
}

func RegisterSimpleCommServer(s grpc.ServiceRegistrar, srv SimpleCommServer) {
	s.RegisterService(&SimpleComm_ServiceDesc, srv)
}

func _SimpleComm_Talk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleCommServer).Talk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleComm_Talk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleCommServer).Talk(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SimpleComm_ServiceDesc is the grpc.ServiceDesc for SimpleComm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleComm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SimpleComm",
	HandlerType: (*SimpleCommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Talk",
			Handler:    _SimpleComm_Talk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SimpleComm.proto",
}
